#!/usr/bin/env python3
"""
SENTINEL Strike v3.0 — Report Generator

Generates professional reports in multiple formats.
"""

import json
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List, Optional
from dataclasses import dataclass


@dataclass
class ReportData:
    """Report data structure."""
    target: str
    started_at: str
    completed_at: str
    iterations: int
    successful_attacks: int
    success_rate: float
    vulnerabilities: List[Dict[str, Any]]
    heads_used: List[str] = None
    stealth_enabled: bool = True
    chatbot_discovery: Optional[Dict[str, Any]] = None  # H7:CHATBOT results


class ReportGenerator:
    """
    Generate Strike reports in multiple formats.

    Supported formats:
    - JSON: Machine-readable
    - Markdown: Human-readable
    - HTML: Web/email
    - SARIF: GitHub Security
    """

    def __init__(self, report_dir: str = "./reports"):
        self.report_dir = Path(report_dir)
        self.report_dir.mkdir(parents=True, exist_ok=True)

    def generate(
        self,
        data: ReportData,
        format: str = "json",
        filename: Optional[str] = None
    ) -> Path:
        """
        Generate report in specified format.

        Args:
            data: Report data
            format: Output format (json, markdown, html, sarif)
            filename: Custom filename (optional)

        Returns:
            Path to generated report
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

        generators = {
            "json": self._generate_json,
            "markdown": self._generate_markdown,
            "md": self._generate_markdown,
            "html": self._generate_html,
            "sarif": self._generate_sarif,
        }

        generator = generators.get(format.lower())
        if not generator:
            raise ValueError(f"Unknown format: {format}")

        content, ext = generator(data)

        if filename:
            filepath = self.report_dir / filename
        else:
            filepath = self.report_dir / f"strike_report_{timestamp}.{ext}"

        filepath.write_text(content, encoding="utf-8")
        return filepath

    def _generate_json(self, data: ReportData) -> tuple:
        """Generate JSON report."""
        content = json.dumps({
            "report_type": "SENTINEL Strike",
            "version": "3.0",
            "generated_at": datetime.now().isoformat(),
            "target": data.target,
            "started_at": data.started_at,
            "completed_at": data.completed_at,
            "summary": {
                "iterations": data.iterations,
                "successful_attacks": data.successful_attacks,
                "success_rate": data.success_rate,
                "stealth_enabled": data.stealth_enabled,
            },
            "vulnerabilities": data.vulnerabilities,
            "heads_used": data.heads_used or [],
        }, indent=2)

        return content, "json"

    def _generate_markdown(self, data: ReportData) -> tuple:
        """Generate Markdown report."""
        vulns_section = ""
        if data.vulnerabilities:
            vulns_section = "\n".join([
                f"### {i}. {v.get('vector', 'Unknown')}\n\n"
                f"- **Severity:** {v.get('severity', 'medium')}\n"
                f"- **Category:** {v.get('category', 'unknown')}\n"
                f"- **Timestamp:** {v.get('timestamp', '')}\n"
                f"- **Response:** `{v.get('response', '')[:200]}...`\n"
                for i, v in enumerate(data.vulnerabilities, 1)
            ])
        else:
            vulns_section = "_No vulnerabilities found._"

        content = f"""# 🎯 SENTINEL Strike Report

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Target

- **URL:** {data.target}
- **Started:** {data.started_at}
- **Completed:** {data.completed_at}

## Summary

| Metric | Value |
|--------|-------|
| Iterations | {data.iterations} |
| Successful Attacks | {data.successful_attacks} |
| Success Rate | {data.success_rate:.1%} |
| Stealth Mode | {"✅ Enabled" if data.stealth_enabled else "⚡ Disabled"} |

## Vulnerabilities Found ({len(data.vulnerabilities)})

{vulns_section}

## Recommendations

1. Review and patch identified vulnerabilities
2. Implement additional guardrails for bypassed categories
3. Enable multi-turn attack detection
4. Consider rate limiting and anomaly detection

---

*Generated by SENTINEL Strike v3.0*
"""
        return content, "md"

    def _generate_html(self, data: ReportData) -> tuple:
        """Generate HTML report."""
        vuln_rows = ""
        for v in data.vulnerabilities:
            severity = v.get("severity", "medium")
            color = {"critical": "#f85149", "high": "#f97583",
                     "medium": "#d29922"}.get(severity, "#8b949e")
            vuln_rows += f"""
            <tr>
                <td>{v.get('vector', 'Unknown')}</td>
                <td>{v.get('category', 'unknown')}</td>
                <td style="color: {color}; font-weight: bold;">{severity.upper()}</td>
                <td>{v.get('timestamp', '')}</td>
            </tr>
            """

        # Generate H7:CHATBOT section if chatbot discovery was done
        chatbot_section = ""
        if data.chatbot_discovery and data.chatbot_discovery.get("total_discovered", 0) > 0:
            cd = data.chatbot_discovery
            endpoint_rows = ""
            for ep in cd.get("endpoints_found", [])[:10]:
                if isinstance(ep, dict):
                    endpoint_rows += f"<tr><td>{ep.get('url', 'N/A')}</td><td>{ep.get('type', 'api')}</td><td>{ep.get('confidence', 0):.0%}</td></tr>"

            chatbot_section = f"""
        <h2>🤖 H7:CHATBOT — AI Endpoint Discovery</h2>
        <div class="summary" style="grid-template-columns: repeat(3, 1fr);">
            <div class="stat">
                <div class="stat-value">{cd.get('total_discovered', 0)}</div>
                <div class="stat-label">Endpoints Found</div>
            </div>
            <div class="stat">
                <div class="stat-value">{len(cd.get('widgets', []))}</div>
                <div class="stat-label">Widgets</div>
            </div>
            <div class="stat">
                <div class="stat-value">{len(cd.get('ai_providers', []))}</div>
                <div class="stat-label">AI Providers</div>
            </div>
        </div>
        <table>
            <tr><th>Endpoint</th><th>Type</th><th>Confidence</th></tr>
            {endpoint_rows or '<tr><td colspan="3">No endpoints discovered</td></tr>'}
        </table>
        """

        content = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>SENTINEL Strike Report</title>
    <style>
        body {{ font-family: 'Segoe UI', sans-serif; background: #0d1117; color: #e6edf3; padding: 40px; }}
        .container {{ max-width: 900px; margin: 0 auto; }}
        h1 {{ color: #f85149; }}
        .summary {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin: 24px 0; }}
        .stat {{ background: #161b22; padding: 20px; border-radius: 8px; text-align: center; }}
        .stat-value {{ font-size: 2rem; font-weight: bold; }}
        .stat-label {{ color: #8b949e; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 24px; }}
        th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #30363d; }}
        th {{ background: #161b22; }}
        .success {{ color: #3fb950; }}
        .danger {{ color: #f85149; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🎯 SENTINEL Strike Report</h1>
        <p><strong>Target:</strong> {data.target}</p>
        <p><strong>Generated:</strong> {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
        
        <div class="summary">
            <div class="stat">
                <div class="stat-value">{data.iterations}</div>
                <div class="stat-label">Iterations</div>
            </div>
            <div class="stat">
                <div class="stat-value danger">{data.successful_attacks}</div>
                <div class="stat-label">Successful</div>
            </div>
            <div class="stat">
                <div class="stat-value">{data.success_rate:.1%}</div>
                <div class="stat-label">Success Rate</div>
            </div>
            <div class="stat">
                <div class="stat-value success">{len(data.vulnerabilities)}</div>
                <div class="stat-label">Vulnerabilities</div>
            </div>
        </div>
        
        {chatbot_section}
        
        <h2>🔓 Vulnerabilities</h2>
        <table>
            <tr>
                <th>Vector</th>
                <th>Category</th>
                <th>Severity</th>
                <th>Timestamp</th>
            </tr>
            {vuln_rows or '<tr><td colspan="4">No vulnerabilities found</td></tr>'}
        </table>
        
        <p style="margin-top: 40px; color: #8b949e; font-size: 0.85rem;">
            Generated by SENTINEL Strike v3.0 | LLM Red Team Platform
        </p>
    </div>
</body>
</html>"""
        return content, "html"

    def _generate_sarif(self, data: ReportData) -> tuple:
        """Generate SARIF format for GitHub Security."""
        results = []
        rules = []

        for i, v in enumerate(data.vulnerabilities):
            rule_id = f"STRIKE-{i+1:03d}"
            severity_map = {"critical": "error",
                            "high": "warning", "medium": "note"}

            rules.append({
                "id": rule_id,
                "name": v.get("vector", "Unknown"),
                "shortDescription": {"text": f"{v.get('category', 'LLM')} vulnerability"},
                "defaultConfiguration": {
                    "level": severity_map.get(v.get("severity", "medium"), "note")
                }
            })

            results.append({
                "ruleId": rule_id,
                "message": {"text": f"Found {v.get('vector', 'vulnerability')} in LLM endpoint"},
                "locations": [{
                    "physicalLocation": {
                        "artifactLocation": {"uri": data.target}
                    }
                }]
            })

        sarif = {
            "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
            "version": "2.1.0",
            "runs": [{
                "tool": {
                    "driver": {
                        "name": "SENTINEL Strike",
                        "version": "3.0.0",
                        "informationUri": "https://github.com/DmitrL-dev/AISecurity",
                        "rules": rules
                    }
                },
                "results": results
            }]
        }

        return json.dumps(sarif, indent=2), "sarif.json"


def generate_report(
    target: str,
    started_at: str,
    completed_at: str,
    iterations: int,
    successful_attacks: int,
    vulnerabilities: List[Dict],
    format: str = "json",
    output_dir: str = "./reports"
) -> Path:
    """
    Convenience function to generate report.

    Returns path to generated file.
    """
    data = ReportData(
        target=target,
        started_at=started_at,
        completed_at=completed_at,
        iterations=iterations,
        successful_attacks=successful_attacks,
        success_rate=successful_attacks / max(iterations, 1),
        vulnerabilities=vulnerabilities,
    )

    generator = ReportGenerator(output_dir)
    return generator.generate(data, format)
