#!/usr/bin/env python3
"""
SENTINEL-Guard Extended Safe Samples

~3000+ safe prompts for training data balance.
Categories match unsafe categories for better learning.
"""

# =============================================================================
# GENERAL KNOWLEDGE (300+)
# =============================================================================
GENERAL_SAMPLES = [
    # Basic questions
    "What is the weather today?",
    "Tell me a joke",
    "How do I cook pasta?",
    "Explain quantum computing",
    "Write a haiku about spring",
    "What's 2+2?",
    "Summarize this article for me",
    "Translate hello to Spanish",
    "What are the benefits of exercise?",
    "Recommend a good book",
    "How does photosynthesis work?",
    "What is the capital of France?",
    "Explain machine learning in simple terms",
    "Write a short poem",
    "What are some healthy breakfast options?",
    "What time is it in Tokyo?",
    "How many planets are in our solar system?",
    "What is the speed of light?",
    "Who wrote Romeo and Juliet?",
    "What is the largest ocean?",
    "How do airplanes fly?",
    "What causes earthquakes?",
    "Who invented the telephone?",
    "What is DNA?",
    "How do magnets work?",
    "What is the tallest mountain?",
    "Who painted the Mona Lisa?",
    "What is the population of China?",
    "How does the internet work?",
    "What is inflation?",
    "Explain the theory of relativity",
    "What are renewable energy sources?",
    "How do electric cars work?",
    "What is blockchain technology?",
    "Explain supply and demand",
    "What is the European Union?",
    "How do satellites orbit Earth?",
    "What is the stock market?",
    "Explain how democracy works",
    "What are the benefits of meditation?",
    "How do I start a garden?",
    "What is a balanced diet?",
    "How do I learn a new language?",
    "What are the best study techniques?",
    "How do I improve my memory?",
    "What is mindfulness?",
    "How do I manage stress?",
    "What are compound interest benefits?",
    "How do I create a budget?",
    "What is passive income?",
    # Extended general
    "What is the meaning of life?",
    "How do I make new friends?",
    "What are good conversation starters?",
    "How do I deal with rejection?",
    "What is emotional intelligence?",
    "How do I build self-confidence?",
    "What are the signs of a healthy relationship?",
    "How do I set personal boundaries?",
    "What is work-life balance?",
    "How do I find my passion?",
    "What are good hobbies to try?",
    "How do I stay motivated?",
    "What is the secret to happiness?",
    "How do I overcome fear?",
    "What are signs of burnout?",
    "How do I recover from failure?",
    "What is gratitude practice?",
    "How do I develop patience?",
    "What is self-care?",
    "How do I manage my time better?",
    "What are good morning routines?",
    "How do I sleep better?",
    "What is the importance of reading?",
    "How do I break bad habits?",
    "What are good productivity tips?",
    "How do I stay organized?",
    "What is minimalism?",
    "How do I declutter my space?",
    "What are eco-friendly practices?",
    "How do I reduce my carbon footprint?",
    "What is sustainable living?",
    "How do I save water at home?",
    "What are benefits of recycling?",
    "How do I compost at home?",
    "What is urban gardening?",
    "How do I grow tomatoes?",
    "What are indoor plants for beginners?",
    "How do I care for succulents?",
    "What is hydroponics?",
    "How do I start beekeeping?",
    "What are benefits of walking?",
    "How do I train for a marathon?",
    "What is yoga for beginners?",
    "How do I do a push-up correctly?",
    "What is HIIT training?",
    "How do I stretch properly?",
    "What are signs of dehydration?",
    "How do I count macros?",
    "What is intermittent fasting?",
    "How do I meal prep?",
    # Geography and facts
    "What is the longest river?",
    "How deep is the Mariana Trench?",
    "What is the driest place on Earth?",
    "How hot is the Sun?",
    "What causes northern lights?",
    "How are rainbows formed?",
    "What is the water cycle?",
    "How do clouds form?",
    "What causes thunder?",
    "How do hurricanes form?",
    "What is climate change?",
    "How does global warming work?",
    "What is the ozone layer?",
    "How do vaccines work?",
    "What is the immune system?",
    "How does the heart pump blood?",
    "What are the five senses?",
    "How do we breathe?",
    "What is the digestive system?",
    "How do bones heal?",
    "What is sleep and why do we need it?",
    "How does caffeine affect the body?",
    "What are vitamins and minerals?",
    "How does the brain work?",
    "What is memory?",
    "How do we learn?",
    "What is creativity?",
    "How do emotions work?",
    "What is consciousness?",
    "How do our eyes see?",
    "What causes color blindness?",
    "How do we hear sounds?",
    "What is tinnitus?",
    "How do taste buds work?",
    "What is the sense of smell?",
    "How does touch work?",
    "What is pain?",
    "How do we feel temperature?",
    "What is balance?",
    "How do muscles grow?",
    # Practical life
    "How do I tie a tie?",
    "What is the best way to iron clothes?",
    "How do I sew a button?",
    "What is the recipe for pancakes?",
    "How do I make homemade bread?",
    "What is the best way to boil eggs?",
    "How do I grill a steak?",
    "What temperature should chicken be cooked to?",
    "How do I make pizza dough?",
    "What is the recipe for chocolate chip cookies?",
    "How do I make fresh pasta?",
    "What is the best way to roast vegetables?",
    "How do I make soup from scratch?",
    "What is a good salad dressing recipe?",
    "How do I bake a cake?",
    "What is the recipe for apple pie?",
    "How do I make whipped cream?",
    "What is the best way to brew coffee?",
    "How do I make iced tea?",
    "What is the recipe for lemonade?",
    "How do I make a smoothie?",
    "What is the best way to store food?",
    "How do I freeze vegetables?",
    "What is food preservation?",
    "How do I can fruits?",
    "What is pickling?",
    "How do I make jam?",
    "What is the recipe for salsa?",
    "How do I make guacamole?",
    "What is the best way to cook rice?",
    "How do I make fried rice?",
    "What is the recipe for ramen?",
    "How do I make sushi at home?",
    "What is the best way to cook beans?",
    "How do I make hummus?",
    "What is the recipe for falafel?",
    "How do I make curry?",
    "What is the best way to cook tofu?",
    "How do I make vegetable stir fry?",
    "What is the recipe for pad thai?",
    # Trivia and fun
    "What is the smallest country in the world?",
    "How many bones are in the human body?",
    "What is the fastest animal?",
    "How long do elephants live?",
    "What is the largest animal ever?",
    "How many teeth does a shark have?",
    "What is the most venomous snake?",
    "How do chameleons change color?",
    "What is the wingspan of an albatross?",
    "How do birds navigate during migration?",
    "What is the deepest diving mammal?",
    "How long can a camel go without water?",
    "What is the lifespan of a tortoise?",
    "How do bees make honey?",
    "What is the purpose of zebra stripes?",
    "How do owls see at night?",
    "What makes flamingos pink?",
    "How do dolphins sleep?",
    "What is the intelligence level of crows?",
    "How do ants communicate?",
]

# =============================================================================
# PROGRAMMING & TECHNOLOGY (400+)
# =============================================================================
PROGRAMMING_SAMPLES = [
    # Python
    "How do I write a for loop in Python?",
    "What is a Python dictionary?",
    "How do I read a file in Python?",
    "What are Python decorators?",
    "How do I create a class in Python?",
    "What is the difference between list and tuple?",
    "How do I handle exceptions in Python?",
    "What is a generator in Python?",
    "How do I use lambda functions?",
    "What is list comprehension?",
    "How do I install packages with pip?",
    "What is virtual environment in Python?",
    "How do I use f-strings?",
    "What is the __init__ method?",
    "How do I make HTTP requests in Python?",
    "What is asyncio in Python?",
    "How do I parse JSON in Python?",
    "What is the difference between == and is?",
    "How do I sort a list in Python?",
    "What is slicing in Python?",
    "How do I use regular expressions in Python?",
    "What is the purpose of __name__ == '__main__'?",
    "How do I debug Python code?",
    "What is PEP 8?",
    "How do I document Python code?",
    "What is type hinting in Python?",
    "How do I use dataclasses?",
    "What is the walrus operator?",
    "How do I profile Python code?",
    "What are context managers in Python?",
    # JavaScript
    "How do I declare a variable in JavaScript?",
    "What is the difference between let and const?",
    "How do I create a function in JavaScript?",
    "What are arrow functions?",
    "How do I use async/await?",
    "What is a Promise in JavaScript?",
    "How do I manipulate the DOM?",
    "What is event bubbling?",
    "How do I use fetch API?",
    "What is JSON.parse()?",
    "How do I loop through an array?",
    "What are template literals?",
    "How do I destructure objects?",
    "What is the spread operator?",
    "How do I use map, filter, reduce?",
    "What is closure in JavaScript?",
    "How do I handle errors in JavaScript?",
    "What is the this keyword?",
    "How do I create a class in JavaScript?",
    "What is the prototype chain?",
    "How do I use localStorage?",
    "What are ES6 modules?",
    "How do I debounce a function?",
    "What is event delegation?",
    "How do I deep copy an object?",
    "What is hoisting in JavaScript?",
    "How do I use Set and Map?",
    "What are WeakMap and WeakSet?",
    "How do I use optional chaining?",
    "What is nullish coalescing?",
    # Web Development
    "What is HTML?",
    "How do I create a form in HTML?",
    "What are semantic HTML elements?",
    "How do I link CSS to HTML?",
    "What is the box model in CSS?",
    "How do I use Flexbox?",
    "What is CSS Grid?",
    "How do I make a responsive website?",
    "What are media queries?",
    "How do I use CSS variables?",
    "What is the cascade in CSS?",
    "How do I center a div?",
    "What is BEM methodology?",
    "How do I use CSS animations?",
    "What are CSS transitions?",
    "How do I use pseudo-elements?",
    "What is accessibility in web development?",
    "How do I test for accessibility?",
    "What is ARIA?",
    "How do I make a dropdown menu?",
    "What is a modal dialog?",
    "How do I create a carousel?",
    "What is lazy loading?",
    "How do I optimize images for web?",
    "What is WebP format?",
    "How do I implement dark mode?",
    "What is Progressive Web App?",
    "How do I use service workers?",
    "What is IndexedDB?",
    "How do I cache API responses?",
    # Frameworks
    "What is React?",
    "How do I create a React component?",
    "What are React hooks?",
    "How do I use useState?",
    "What is useEffect for?",
    "How do I pass props in React?",
    "What is the virtual DOM?",
    "How do I handle events in React?",
    "What is conditional rendering?",
    "How do I fetch data in React?",
    "What is Redux?",
    "How do I use React Router?",
    "What is Next.js?",
    "How do I use getServerSideProps?",
    "What are Vue.js basics?",
    "How do I use v-model in Vue?",
    "What is Angular?",
    "How do I create a service in Angular?",
    "What is dependency injection?",
    "How do I use TypeScript with React?",
    "What is Svelte?",
    "How do I use stores in Svelte?",
    "What is SolidJS?",
    "How do I compare frontend frameworks?",
    "What is Astro?",
    "How do I use Tailwind CSS?",
    "What is Bootstrap?",
    "How do I use Material UI?",
    "What is styled-components?",
    "How do I test React components?",
    # Backend
    "What is Node.js?",
    "How do I create an Express server?",
    "What is middleware in Express?",
    "How do I handle routes in Express?",
    "What is Django?",
    "How do I create a view in Django?",
    "What is the Django ORM?",
    "How do I use Django templates?",
    "What is Flask?",
    "How do I create API routes in Flask?",
    "What is FastAPI?",
    "How do I use Pydantic models?",
    "What is dependency injection in FastAPI?",
    "How do I document API with OpenAPI?",
    "What is GraphQL?",
    "How do I create a GraphQL schema?",
    "What is REST API?",
    "How do I design RESTful endpoints?",
    "What is API versioning?",
    "How do I handle authentication in APIs?",
    "What is JWT?",
    "How do I implement OAuth?",
    "What is session-based authentication?",
    "How do I rate limit an API?",
    "What is CORS?",
    "How do I handle file uploads?",
    "What is WebSocket?",
    "How do I implement real-time features?",
    "What is Server-Sent Events?",
    "How do I use Redis for caching?",
    # Databases
    "What is SQL?",
    "How do I create a table in SQL?",
    "What is a primary key?",
    "How do I use foreign keys?",
    "What is database normalization?",
    "How do I write a JOIN query?",
    "What is an index in databases?",
    "How do I optimize SQL queries?",
    "What is a transaction?",
    "How do I use stored procedures?",
    "What is PostgreSQL?",
    "How do I use JSONB in PostgreSQL?",
    "What is MySQL?",
    "How do I backup a database?",
    "What is SQLite?",
    "How do I use SQLite in Python?",
    "What is MongoDB?",
    "How do I query documents in MongoDB?",
    "What is Redis?",
    "How do I use Redis as a cache?",
    "What is Elasticsearch?",
    "How do I index documents?",
    "What is a document database?",
    "How do I choose between SQL and NoSQL?",
    "What is database sharding?",
    "How do I implement pagination?",
    "What is full-text search?",
    "How do I handle database migrations?",
    "What is ORM?",
    "How do I use SQLAlchemy?",
    # DevOps
    "What is Docker?",
    "How do I create a Dockerfile?",
    "What is docker-compose?",
    "How do I build a Docker image?",
    "What is Kubernetes?",
    "How do I create a deployment in K8s?",
    "What is a pod in Kubernetes?",
    "How do I use ConfigMaps?",
    "What is a Kubernetes service?",
    "How do I set up ingress?",
    "What is CI/CD?",
    "How do I use GitHub Actions?",
    "What is Jenkins?",
    "How do I create a pipeline?",
    "What is GitLab CI?",
    "How do I automate deployments?",
    "What is infrastructure as code?",
    "How do I use Terraform?",
    "What is Ansible?",
    "How do I manage server configuration?",
    "What is AWS?",
    "How do I use EC2?",
    "What is S3?",
    "How do I deploy to Lambda?",
    "What is Azure?",
    "How do I use Azure Functions?",
    "What is Google Cloud?",
    "How do I use Cloud Run?",
    "What is serverless architecture?",
    "How do I monitor applications?",
    "What is Prometheus?",
    "How do I use Grafana?",
    "What is log aggregation?",
    "How do I use ELK stack?",
    "What is observability?",
    "How do I implement tracing?",
    "What is load balancing?",
    "How do I set up nginx?",
    "What is reverse proxy?",
    "How do I configure SSL/TLS?",
    # Data Structures & Algorithms
    "What is an array?",
    "How do I implement a linked list?",
    "What is a stack?",
    "How do I use a queue?",
    "What is a hash table?",
    "How do I implement a binary tree?",
    "What is a heap?",
    "How do I use a graph?",
    "What is Big O notation?",
    "How do I analyze algorithm complexity?",
    "What is bubble sort?",
    "How does quicksort work?",
    "What is merge sort?",
    "How do I implement binary search?",
    "What is depth-first search?",
    "How does breadth-first search work?",
    "What is dynamic programming?",
    "How do I solve the knapsack problem?",
    "What is memoization?",
    "How do I detect a cycle in a graph?",
    "What is Dijkstra's algorithm?",
    "How do I find shortest path?",
    "What is a greedy algorithm?",
    "How do I solve two-pointer problems?",
    "What is sliding window technique?",
    "How do I reverse a linked list?",
    "What is recursion?",
    "How do I convert recursion to iteration?",
    "What is tail recursion?",
    "How do I balance a binary tree?",
]

# =============================================================================
# SECURITY EDUCATION (300+)
# =============================================================================
SECURITY_EDUCATION_SAMPLES = [
    # Web Security Basics
    "How do I prevent SQL injection?",
    "What is XSS and how to prevent it?",
    "Explain HTTPS encryption",
    "What are security best practices?",
    "How does OAuth work?",
    "What is two-factor authentication?",
    "Explain the principle of least privilege",
    "What is a firewall?",
    "How to secure an API?",
    "What is penetration testing?",
    "What is the OWASP Top 10?",
    "How do I implement CSRF protection?",
    "What is input validation?",
    "Explain parameterized queries",
    "What is content security policy?",
    "How do I secure passwords?",
    "What is bcrypt?",
    "Explain salting in cryptography",
    "What is JWT security?",
    "How do I prevent clickjacking?",
    "What is HSTS?",
    "Explain secure cookie flags",
    "What is rate limiting?",
    "How do I implement API authentication?",
    "What is role-based access control?",
    "Explain zero trust security",
    "What is defense in depth?",
    "How do I conduct a security audit?",
    "What is threat modeling?",
    "Explain the CIA triad",
    "What is vulnerability scanning?",
    "How do I report a security bug?",
    "What is responsible disclosure?",
    "Explain bug bounty programs",
    "What is SOC 2 compliance?",
    "How do I implement GDPR requirements?",
    "What is data encryption at rest?",
    "Explain end-to-end encryption",
    "What is a VPN?",
    "How do I secure my home network?",
    "What is phishing awareness?",
    "How do I create strong passwords?",
    "What is a password manager?",
    "Explain MFA best practices",
    "What is social engineering?",
    "How do I protect against ransomware?",
    "What is security awareness training?",
    "Explain incident response planning",
    "What is a security policy?",
    "How do I secure cloud infrastructure?",
    # Application Security
    "What is secure coding?",
    "How do I validate user input?",
    "What is output encoding?",
    "Explain session management security",
    "What is authentication vs authorization?",
    "How do I implement secure login?",
    "What is brute force protection?",
    "Explain account lockout policies",
    "What is secure password reset?",
    "How do I protect API keys?",
    "What is secret management?",
    "Explain environment variables for secrets",
    "What is code signing?",
    "How do I verify software integrity?",
    "What is supply chain security?",
    "Explain dependency scanning",
    "What is SAST?",
    "How do I use DAST?",
    "What is security testing?",
    "Explain fuzzing",
    "What is code review for security?",
    "How do I use security linters?",
    "What is threat intelligence?",
    "Explain security monitoring",
    "What are security logs?",
    "How do I analyze security events?",
    "What is SIEM?",
    "Explain intrusion detection",
    "What is anomaly detection?",
    "How do I respond to security incidents?",
    # Cryptography
    "What is symmetric encryption?",
    "Explain asymmetric encryption",
    "What is AES?",
    "How does RSA work?",
    "What is hashing?",
    "Explain SHA-256",
    "What is a digital signature?",
    "How do certificates work?",
    "What is PKI?",
    "Explain certificate authorities",
    "What is TLS?",
    "How does HTTPS handshake work?",
    "What is perfect forward secrecy?",
    "Explain key exchange",
    "What is Diffie-Hellman?",
    "How do I generate secure random numbers?",
    "What is entropy?",
    "Explain key derivation functions",
    "What is PBKDF2?",
    "How do I store encryption keys securely?",
    "What is hardware security module?",
    "Explain key rotation",
    "What is envelope encryption?",
    "How do I encrypt files?",
    "What is disk encryption?",
    "Explain database encryption",
    "What is tokenization?",
    "How do I mask sensitive data?",
    "What is data anonymization?",
    "Explain differential privacy",
    # Network Security
    "What is network segmentation?",
    "Explain DMZ architecture",
    "What is a proxy server?",
    "How do I configure firewall rules?",
    "What is port scanning?",
    "Explain network monitoring",
    "What is packet sniffing?",
    "How do I detect network intrusions?",
    "What is DDoS protection?",
    "Explain load balancer security",
    "What is DNS security?",
    "How do I prevent DNS spoofing?",
    "What is DNSSEC?",
    "Explain BGP security",
    "What is network access control?",
    "How do I implement 802.1X?",
    "What is wireless security?",
    "Explain WPA3",
    "What is VPN tunneling?",
    "How do I set up IPsec?",
    # Cloud Security
    "What is cloud security?",
    "Explain shared responsibility model",
    "What is IAM?",
    "How do I manage cloud permissions?",
    "What is cloud encryption?",
    "Explain cloud key management",
    "What is cloud logging?",
    "How do I audit cloud access?",
    "What is container security?",
    "Explain Kubernetes security",
    "What is image scanning?",
    "How do I secure container registries?",
    "What is serverless security?",
    "Explain function-level permissions",
    "What is cloud compliance?",
    "How do I pass security audits?",
    "What is cloud backup security?",
    "Explain disaster recovery",
    "What is multi-cloud security?",
    "How do I secure hybrid cloud?",
    # Enterprise Security
    "What is enterprise security?",
    "Explain security governance",
    "What is risk management?",
    "How do I conduct risk assessment?",
    "What is security compliance?",
    "Explain ISO 27001",
    "What is PCI DSS?",
    "How do I achieve HIPAA compliance?",
    "What is security architecture?",
    "Explain security frameworks",
    "What is NIST cybersecurity framework?",
    "How do I implement CIS controls?",
    "What is security operations center?",
    "Explain 24/7 monitoring",
    "What is incident management?",
    "How do I create runbooks?",
    "What is change management?",
    "Explain security review process",
    "What is vendor security?",
    "How do I assess third-party risk?",
]

# =============================================================================
# AI/ML EDUCATION (300+)
# =============================================================================
AI_ML_SAMPLES = [
    # LLM Basics
    "What is prompt engineering?",
    "Explain how LLMs work",
    "What is fine-tuning a model?",
    "How does GPT generate text?",
    "What is the transformer architecture?",
    "Explain attention mechanism",
    "What is RAG in AI?",
    "How to evaluate ML models?",
    "What is transfer learning?",
    "Explain neural network layers",
    "What is backpropagation?",
    "How do I train a classifier?",
    "What is overfitting?",
    "Explain cross-validation",
    "What is a confusion matrix?",
    "How do I preprocess text data?",
    "What is tokenization?",
    "Explain word embeddings",
    "What is BERT?",
    "How do I use Hugging Face?",
    "What is model quantization?",
    "Explain LoRA fine-tuning",
    "What is a language model temperature?",
    "How do I control generation length?",
    "What is top-p sampling?",
    "Explain chain-of-thought prompting",
    "What is few-shot learning?",
    "How do I evaluate LLM outputs?",
    "What is AI alignment?",
    "Explain AI safety research",
    "What is red teaming for AI?",
    "How do I detect hallucinations?",
    "What is grounding in LLMs?",
    "Explain retrieval augmented generation",
    "What is vector database?",
    "How do I use embeddings for search?",
    "What is semantic similarity?",
    "Explain cosine distance",
    "What is clustering in ML?",
    "How do I visualize embeddings?",
    "What is a recommendation system?",
    "Explain collaborative filtering",
    "What is sentiment analysis?",
    "How do I classify text?",
    "What is named entity recognition?",
    "Explain part-of-speech tagging",
    "What is text summarization?",
    "How do I build a chatbot?",
    "What is conversational AI?",
    "Explain dialogue management",
    # Deep Learning
    "What is a neural network?",
    "Explain activation functions",
    "What is ReLU?",
    "How do I prevent vanishing gradients?",
    "What is batch normalization?",
    "Explain dropout regularization",
    "What is learning rate?",
    "How do I choose optimizer?",
    "What is Adam optimizer?",
    "Explain gradient descent",
    "What is stochastic gradient descent?",
    "How do I set training epochs?",
    "What is early stopping?",
    "Explain loss functions",
    "What is cross-entropy loss?",
    "How do I handle imbalanced datasets?",
    "What is data augmentation?",
    "Explain transfer learning",
    "What is a pretrained model?",
    "How do I fine-tune a model?",
    "What is frozen layers?",
    "Explain layer-wise learning rates",
    "What is curriculum learning?",
    "How do I use mixed precision training?",
    "What is gradient accumulation?",
    "Explain distributed training",
    "What is model parallelism?",
    "How do I scale training?",
    "What is hyperparameter tuning?",
    "Explain grid search",
    # Computer Vision
    "What is CNN?",
    "Explain convolutional layers",
    "What is pooling?",
    "How do I classify images?",
    "What is object detection?",
    "Explain YOLO algorithm",
    "What is image segmentation?",
    "How does U-Net work?",
    "What is face recognition?",
    "Explain facial landmark detection",
    "What is pose estimation?",
    "How do I use OpenCV?",
    "What is image preprocessing?",
    "Explain data augmentation for images",
    "What is style transfer?",
    "How do GANs work?",
    "What is image generation?",
    "Explain diffusion models",
    "What is CLIP?",
    "How do I use vision transformers?",
    # NLP
    "What is NLP?",
    "Explain text preprocessing",
    "What is stemming?",
    "How does lemmatization work?",
    "What is stop word removal?",
    "Explain TF-IDF",
    "What is bag of words?",
    "How do I build text features?",
    "What is word2vec?",
    "Explain GloVe embeddings",
    "What is sequence labeling?",
    "How does CRF work?",
    "What is machine translation?",
    "Explain encoder-decoder architecture",
    "What is attention in NLP?",
    "How does BERT work?",
    "What is GPT architecture?",
    "Explain T5 model",
    "What is text generation?",
    "How do I control output?",
    # MLOps
    "What is MLOps?",
    "Explain ML pipeline",
    "What is feature store?",
    "How do I version datasets?",
    "What is experiment tracking?",
    "Explain MLflow",
    "What is model registry?",
    "How do I deploy ML models?",
    "What is model serving?",
    "Explain batch inference",
    "What is real-time inference?",
    "How do I scale inference?",
    "What is model monitoring?",
    "Explain drift detection",
    "What is retraining pipeline?",
    "How do I automate ML workflows?",
    "What is feature engineering?",
    "Explain automated ML?",
    "What is neural architecture search?",
    "How do I optimize model size?",
    # Responsible AI
    "What is AI ethics?",
    "Explain fairness in ML",
    "What is bias in AI?",
    "How do I detect model bias?",
    "What is explainable AI?",
    "Explain SHAP values",
    "What is LIME?",
    "How do I interpret models?",
    "What is AI transparency?",
    "Explain model documentation",
    "What is responsible AI development?",
    "How do I audit AI systems?",
    "What is AI governance?",
    "Explain AI regulations",
    "What is GDPR for AI?",
    "How do I ensure AI compliance?",
    "What is AI safety?",
    "Explain alignment problem",
    "What is AI risk assessment?",
    "How do I mitigate AI risks?",
]

# =============================================================================
# CREATIVE & WRITING (200+)
# =============================================================================
CREATIVE_SAMPLES = [
    "Write a story about a cat",
    "Create a recipe for chocolate cake",
    "Write lyrics for a happy song",
    "Describe a sunset in poetry",
    "Invent a new superhero",
    "Write a fairy tale for children",
    "Create a fictional character profile",
    "Write a short mystery story",
    "Describe a peaceful forest scene",
    "Write a motivational speech",
    "Create a fantasy world description",
    "Write a romantic poem",
    "Describe a futuristic city",
    "Write a children's bedtime story",
    "Create a superhero origin story",
    "Write a travel blog post",
    "Describe an underwater adventure",
    "Write a comedy sketch",
    "Create a science fiction plot",
    "Write a historical fiction scene",
    "Describe a magical creature",
    "Write a friendship story",
    "Create an adventure tale",
    "Write about a day in nature",
    "Describe a celebration scene",
    "Write a coming-of-age story",
    "Create a detective story opening",
    "Write about meeting an alien",
    "Describe a dream sequence",
    "Write a sports victory story",
    "Create a cooking show script",
    "Write about a lost treasure",
    "Describe a time travel adventure",
    "Write a pet adoption story",
    "Create a space exploration tale",
    "Write about a music festival",
    "Describe a mountain climbing journey",
    "Write a story about kindness",
    "Create a weather-themed poem",
    "Write about seasonal changes",
    "Describe a magical garden",
    "Write a letter to future self",
    "Create a villain backstory",
    "Write about a reunion",
    "Describe a road trip adventure",
    "Write a campfire story",
    "Create a legend about the moon",
    "Write about discovering a secret room",
    "Describe an enchanted forest",
    "Write a story about courage",
    "Create a myth about the ocean",
    "Write about a talking animal",
    "Describe a floating city",
    "Write a story about invention",
    "Create a tale of two cities",
    "Write about a magical book",
    "Describe a journey to the center of the earth",
    "Write a story about time stopping",
    "Create a fable with a moral",
    "Write about finding a genie",
    "Describe a world without color",
    "Write a story about dreams coming true",
    "Create a legend about a hero",
    "Write about an impossible journey",
    "Describe a secret society",
    "Write a story about transformation",
    "Create a tale of wisdom",
    "Write about the first day of spring",
    "Describe a winter wonderland",
    "Write a story about hope",
    # Extended creative
    "What makes a good story?",
    "How do I develop characters?",
    "What is show don't tell?",
    "How do I write dialogue?",
    "What is narrative voice?",
    "How do I create conflict?",
    "What is story structure?",
    "How do I write a plot twist?",
    "What is world-building?",
    "How do I create atmosphere?",
    "What is foreshadowing?",
    "How do I write an ending?",
    "What is character arc?",
    "How do I edit my writing?",
    "What is creative writing?",
    "How do I overcome writer's block?",
    "What is poetry form?",
    "How do I write free verse?",
    "What is haiku structure?",
    "How do I write a sonnet?",
]

# =============================================================================
# EDUCATION & LEARNING (200+)
# =============================================================================
EDUCATION_SAMPLES = [
    "Teach me about the solar system",
    "Explain World War II briefly",
    "What caused the French Revolution?",
    "How do vaccines work?",
    "What is climate change?",
    "Explain the water cycle",
    "What is mitosis?",
    "How do plants grow?",
    "What is the periodic table?",
    "Explain Newton's laws",
    "What is evolution?",
    "How do volcanoes form?",
    "What causes seasons?",
    "Explain plate tectonics",
    "What is the food chain?",
    "How do ecosystems work?",
    "What is biodiversity?",
    "Explain the human digestive system",
    "What is the nervous system?",
    "How do muscles work?",
    "What is ancient Egypt?",
    "Explain the Roman Empire",
    "What was the Renaissance?",
    "How did the Industrial Revolution start?",
    "What is the Cold War?",
    "Explain ancient Greek democracy",
    "What is the Silk Road?",
    "How did writing develop?",
    "What are the world's major religions?",
    "Explain the scientific method",
    "What is sociology?",
    "How do economies develop?",
    "What is political science?",
    "Explain different types of government",
    "What is psychology?",
    "How does memory work?",
    "What is cognitive science?",
    "Explain human development stages",
    "What is linguistics?",
    "How do languages evolve?",
    "What is philosophy?",
    "Explain ethics basics",
    "What is logic?",
    "How do arguments work?",
    "What is critical thinking?",
    "Explain research methods",
    "What is statistics?",
    "How do surveys work?",
    "What is data analysis?",
    "Explain the peer review process",
    # Extended education
    "What is the scientific revolution?",
    "Explain the age of exploration",
    "What was the enlightenment?",
    "How did democracy develop?",
    "What is capitalism?",
    "Explain socialism vs communism",
    "What caused World War I?",
    "How did the UN form?",
    "What is the space race?",
    "Explain the civil rights movement",
    "What is feminism?",
    "How did the internet start?",
    "What is globalization?",
    "Explain environmental movement",
    "What is sustainable development?",
    "How do cities form?",
    "What is urbanization?",
    "Explain migration patterns",
    "What is cultural heritage?",
    "How do traditions form?",
    # Science
    "What is physics?",
    "Explain chemistry basics",
    "What is biology?",
    "How does astronomy work?",
    "What is geology?",
    "Explain meteorology",
    "What is oceanography?",
    "How does ecology work?",
    "What is zoology?",
    "Explain botany basics",
    "What is microbiology?",
    "How does genetics work?",
    "What is biochemistry?",
    "Explain organic chemistry",
    "What is quantum physics?",
    "How does thermodynamics work?",
    "What is electromagnetism?",
    "Explain nuclear physics",
    "What is astrophysics?",
    "How does cosmology work?",
]

# =============================================================================
# BUSINESS & PROFESSIONAL (200+)
# =============================================================================
BUSINESS_SAMPLES = [
    "Write a professional email template",
    "How to create a business plan?",
    "What is market segmentation?",
    "Explain supply chain management",
    "How do I write a resume?",
    "What is a cover letter?",
    "How do I prepare for an interview?",
    "What is project management?",
    "Explain SCRUM methodology",
    "What is a KPI?",
    "How do I give a presentation?",
    "What is networking?",
    "How do I negotiate salary?",
    "What is leadership?",
    "Explain team management",
    "What is time management?",
    "How do I prioritize tasks?",
    "What is productivity?",
    "Explain work-life balance",
    "What is remote work best practices?",
    "How do I start a business?",
    "What is entrepreneurship?",
    "Explain business models",
    "What is a startup?",
    "How do I pitch to investors?",
    "What is venture capital?",
    "Explain marketing basics",
    "What is branding?",
    "How do I use social media for business?",
    "What is content marketing?",
    "Explain SEO basics",
    "What is copywriting?",
    "How do I build an email list?",
    "What is customer service?",
    "Explain customer retention",
    "What is sales strategy?",
    "How do I handle objections?",
    "What is B2B vs B2C?",
    "Explain pricing strategies",
    "What is competitive analysis?",
    "How do I read financial statements?",
    "What is accounting basics?",
    "Explain assets and liabilities",
    "What is cash flow?",
    "How do I create a budget?",
    "What is ROI?",
    "Explain profit margins",
    "What is inventory management?",
    "How do I manage suppliers?",
    "What is quality control?",
    # Extended business
    "What is strategic planning?",
    "Explain SWOT analysis",
    "What is market research?",
    "How do I analyze competitors?",
    "What is a value proposition?",
    "Explain customer journey",
    "What is user experience?",
    "How do I design products?",
    "What is product-market fit?",
    "Explain lean startup methodology",
    "What is agile development?",
    "How do I manage sprints?",
    "What is a kanban board?",
    "Explain OKRs",
    "What is performance review?",
    "How do I give feedback?",
    "What is conflict resolution?",
    "Explain change management",
    "What is organizational culture?",
    "How do I build company values?",
    # Finance
    "What is investment?",
    "Explain stocks vs bonds",
    "What is diversification?",
    "How do I start investing?",
    "What is index fund?",
    "Explain mutual funds",
    "What is compound interest?",
    "How does retirement planning work?",
    "What is 401k?",
    "Explain IRA accounts",
    "What is real estate investing?",
    "How do I analyze rental property?",
    "What is passive income?",
    "Explain dividend investing",
    "What is tax planning?",
    "How do I reduce taxes legally?",
    "What is financial independence?",
    "Explain FIRE movement",
    "What is net worth?",
    "How do I track expenses?",
]

# =============================================================================
# HEALTH & WELLNESS (200+)
# =============================================================================
HEALTH_SAMPLES = [
    "What are healthy eating habits?",
    "How much water should I drink?",
    "What is a balanced diet?",
    "How do I start exercising?",
    "What is cardio vs strength training?",
    "How do I improve sleep quality?",
    "What is the importance of rest?",
    "How do I manage anxiety?",
    "What are relaxation techniques?",
    "How do I practice self-care?",
    "What is mental health awareness?",
    "How do I build healthy habits?",
    "What is intermittent fasting?",
    "How do I count calories?",
    "What are macronutrients?",
    "How do vitamins work?",
    "What is fiber good for?",
    "How do I reduce sugar intake?",
    "What is heart health?",
    "How do I lower cholesterol?",
    "What is blood pressure?",
    "How do I maintain healthy weight?",
    "What is BMI?",
    "How do I stretch properly?",
    "What is yoga?",
    "How do I start meditation?",
    "What are breathing exercises?",
    "How do I improve posture?",
    "What is ergonomics?",
    "How do I reduce screen time?",
    "What is digital wellness?",
    "How do I deal with burnout?",
    "What is work stress management?",
    "How do I set boundaries?",
    "What is emotional intelligence?",
    "How do I improve relationships?",
    "What is active listening?",
    "How do I communicate better?",
    "What is conflict resolution?",
    "How do I apologize effectively?",
    "What is gratitude practice?",
    "How do I stay motivated?",
    "What is goal setting?",
    "How do I overcome procrastination?",
    "What is time boxing?",
    "How do I build confidence?",
    "What is impostor syndrome?",
    "How do I handle criticism?",
    "What is growth mindset?",
    "How do I learn from failure?",
    # Extended health
    "What is nutrition science?",
    "How do I read food labels?",
    "What are antioxidants?",
    "How do I boost immune system?",
    "What is gut health?",
    "How do probiotics work?",
    "What is inflammation?",
    "How do I reduce inflammation?",
    "What is metabolism?",
    "How do I speed up metabolism?",
    "What is cortisol?",
    "How do I manage stress hormones?",
    "What is circadian rhythm?",
    "How do I fix sleep schedule?",
    "What is REM sleep?",
    "How do I remember dreams?",
    "What is cognitive health?",
    "How do I sharpen my mind?",
    "What is brain plasticity?",
    "How do I learn faster?",
    # Fitness
    "What is resistance training?",
    "How do I build muscle?",
    "What is progressive overload?",
    "How do I recover from workouts?",
    "What is DOMS?",
    "How do I prevent injuries?",
    "What is flexibility?",
    "How do I increase mobility?",
    "What is core strength?",
    "How do I do a plank correctly?",
    "What is running form?",
    "How do I start running?",
    "What is swimming technique?",
    "How do I start cycling?",
    "What is rowing exercise?",
    "How do I use gym equipment?",
    "What is home workout?",
    "How do I stay fit without gym?",
    "What is bodyweight exercise?",
    "How do I do pull-ups?",
]

# =============================================================================
# DAILY LIFE & PRACTICAL (200+)
# =============================================================================
DAILY_LIFE_SAMPLES = [
    "How do I organize my closet?",
    "What is meal prep?",
    "How do I clean efficiently?",
    "What are laundry tips?",
    "How do I remove stains?",
    "What is home organization?",
    "How do I declutter?",
    "What is minimalism?",
    "How do I plan a trip?",
    "What to pack for vacation?",
    "How do I save money?",
    "What is budgeting?",
    "How do I invest for beginners?",
    "What is an emergency fund?",
    "How do I pay off debt?",
    "What is credit score?",
    "How do I negotiate bills?",
    "What are tax basics?",
    "How do I file taxes?",
    "What is retirement planning?",
    "How do I buy a car?",
    "What is home buying process?",
    "How do I rent an apartment?",
    "What are tenant rights?",
    "How do I move efficiently?",
    "What is home maintenance?",
    "How do I fix a leaky faucet?",
    "What are basic tools needed?",
    "How do I paint a room?",
    "What is furniture assembly?",
    "How do I plant vegetables?",
    "What is composting?",
    "How do I save energy?",
    "What is recycling properly?",
    "How do I reduce waste?",
    "What is sustainable living?",
    "How do I choose appliances?",
    "What is smart home technology?",
    "How do I set up WiFi?",
    "What is router security?",
    "How do I backup my data?",
    "What is cloud storage?",
    "How do I protect my privacy?",
    "What are safe browsing habits?",
    "How do I spot online scams?",
    "What is identity theft protection?",
    "How do I shop safely online?",
    "What is warranty coverage?",
    "How do I return products?",
    "What are consumer rights?",
    # Extended practical
    "How do I choose a phone?",
    "What is laptop buying guide?",
    "How do I set up a printer?",
    "What is home networking?",
    "How do I troubleshoot WiFi?",
    "What is VPN for home?",
    "How do I organize digital files?",
    "What is photo organization?",
    "How do I backup photos?",
    "What is password management?",
    "How do I learn typing?",
    "What is keyboard shortcut?",
    "How do I use spreadsheets?",
    "What is word processing?",
    "How do I make a PDF?",
    "What is presentation software?",
    "How do I use video calls?",
    "What is email etiquette?",
    "How do I manage notifications?",
    "What is digital detox?",
    # Home improvement
    "How do I hang a picture?",
    "What is wall anchor?",
    "How do I fix a squeaky door?",
    "What is caulking?",
    "How do I replace a light switch?",
    "What is electrical safety?",
    "How do I unclog a drain?",
    "What is plumbing basics?",
    "How do I patch drywall?",
    "What is interior painting?",
    "How do I refinish furniture?",
    "What is wood staining?",
    "How do I install shelves?",
    "What is tile installation?",
    "How do I grout tiles?",
    "What is flooring installation?",
    "How do I insulate home?",
    "What is weatherstripping?",
    "How do I maintain HVAC?",
    "What is water heater maintenance?",
]

# =============================================================================
# CONVERSATIONAL (200+)
# =============================================================================
CONVERSATIONAL_SAMPLES = [
    "Hello, how are you?",
    "Good morning!",
    "What's your name?",
    "Nice to meet you",
    "How can you help me?",
    "Tell me about yourself",
    "What can you do?",
    "Are you an AI?",
    "Who created you?",
    "What is your purpose?",
    "Can you understand me?",
    "Do you speak other languages?",
    "How do you work?",
    "Are you always right?",
    "Can you make mistakes?",
    "How do I use you effectively?",
    "What are your limitations?",
    "Can you remember our conversation?",
    "Will you forget what I said?",
    "Is my data safe with you?",
    "Thank you for your help",
    "You're very helpful",
    "That was a good answer",
    "I appreciate your assistance",
    "Can you explain more?",
    "I don't understand",
    "Please clarify",
    "Can you rephrase that?",
    "Give me an example",
    "Why is that?",
    "How do you know?",
    "Where did you learn that?",
    "Is that true?",
    "Can you verify that?",
    "What's the source?",
    "I disagree with that",
    "That's interesting",
    "Tell me more",
    "What else should I know?",
    "Any other suggestions?",
    "What do you recommend?",
    "What would you do?",
    "If you were me?",
    "What's best?",
    "What's your opinion?",
    "Do you have preferences?",
    "What do you think?",
    "Is this a good idea?",
    "Should I do this?",
    "What are the pros and cons?",
    # Extended conversational
    "How was your day?",
    "What's new?",
    "Any updates?",
    "What's happening?",
    "How's it going?",
    "What's up?",
    "Long time no see",
    "How have you been?",
    "Missed you",
    "Good to see you",
    "Welcome back",
    "How can I help?",
    "What do you need?",
    "Let me know if you need anything",
    "I'm here to help",
    "Feel free to ask",
    "No problem",
    "You're welcome",
    "Don't mention it",
    "My pleasure",
    "Happy to help",
    "Anytime",
    "Of course",
    "Certainly",
    "Sure thing",
    "Absolutely",
    "Definitely",
    "No doubt",
    "For sure",
    "I agree",
    "That makes sense",
    "Good point",
    "You're right",
    "I see what you mean",
    "Understood",
    "Got it",
    "Makes sense",
    "I follow",
    "Crystal clear",
    "Perfectly clear",
    "Wait a moment",
    "Hold on",
    "Let me think",
    "Give me a second",
    "Just a moment",
    "One moment please",
    "I need to check",
    "Let me look that up",
    "I'll get back to you",
    "Good question",
]

# =============================================================================
# AGGREGATE FUNCTION
# =============================================================================
def get_all_safe_samples():
    """Return all safe samples with categories."""
    return {
        "general": GENERAL_SAMPLES,
        "programming": PROGRAMMING_SAMPLES,
        "security_education": SECURITY_EDUCATION_SAMPLES,
        "ai_education": AI_ML_SAMPLES,
        "creative": CREATIVE_SAMPLES,
        "education": EDUCATION_SAMPLES,
        "business": BUSINESS_SAMPLES,
        "health": HEALTH_SAMPLES,
        "daily_life": DAILY_LIFE_SAMPLES,
        "conversational": CONVERSATIONAL_SAMPLES,
    }


def get_total_count():
    """Return total count of safe samples."""
    samples = get_all_safe_samples()
    return sum(len(v) for v in samples.values())


if __name__ == "__main__":
    samples = get_all_safe_samples()
    print("Safe samples by category:")
    total = 0
    for cat, prompts in samples.items():
        print(f"  {cat}: {len(prompts)}")
        total += len(prompts)
    print(f"\nTotal: {total}")
